---
AWSTemplateFormatVersion: 2010-09-09
Description: cloudfront distribution
Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: True
        HttpVersion: http2
        IPV6Enabled: True
        DefaultRootObject: index.html
        Aliases: [AWS_CLOUDFRONT_ALIAS]
        ViewerCertificate:
          AcmCertificateArn: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/AWS_ACM_CERTIFICATE_ID"
          MinimumProtocolVersion: "TLSv1"
          SslSupportMethod: "sni-only"
        DefaultCacheBehavior:
          AllowedMethods:
            ["GET", "HEAD", "OPTIONS", "PUT", "PATCH", "POST", "DELETE"]
          CachedMethods: ["GET", "HEAD"]
          CachePolicyId: !Ref "CachePolicy"
          OriginRequestPolicyId: !Ref "OriginRequestPolicy"
          ResponseHeadersPolicyId: !Ref "ResponseHeadersPolicy"
          Compress: True
          TargetOriginId: site-origin
          ViewerProtocolPolicy: https-only
        Origins:
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            Id: site-origin
            DomainName: ORIGIN_SERVER
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 30
              OriginSSLProtocols: [TLSv1.2]

  # 缓存策略
  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: Crazy-CachePolicy-INSTANCE_ID
        Comment: "My Cache Policy"
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: True
          EnableAcceptEncodingGzip: True
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  # 源请求策略
  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: Crazy-OriginRequestPolicy-INSTANCE_ID
        Comment: "My Origin Request Policy"
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Sec-WebSocket-Key
            - Sec-WebSocket-Version
            - Sec-WebSocket-Protocol
            - Sec-WebSocket-Accept
            - Sec-WebSocket-Extensions
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: none

  # 响应标头策略
  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: Crazy-ResponseHeadersPolicy-INSTANCE_ID
        CustomHeadersConfig:
          Items:
            - Header: X-Custom-Header
              Value: Hello World
              Override: true
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: SAMEORIGIN
            Override: false
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: false
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: false
            Preload: false
            Override: false
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: false
