FROM quay.io/jupyter/scipy-notebook:2024-10-09

# Reference:
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
# https://github.com/jupyter/docker-stacks/blob/main/images/minimal-notebook/Dockerfile
# https://github.com/jupyter/docker-stacks/blob/main/images/scipy-notebook/Dockerfile
# https://github.com/jupyter/docker-stacks/blob/main/images/pytorch-notebook/Dockerfile

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
