name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      context:
        description: 'Specify build context'
        required: true
        default: 'cloudreve'
      dockerfile:
        description: 'Specify Dockerfile location'
        required: true
        default: 'Dockerfile'
      description:
        description: 'Short description(<100 characters)'
        required: false
        default: ''
      readme_filepath:
        description: 'Specify README.md file location'
        required: true
        default: 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/386
        file: ${{ github.event.inputs.context }}/${{ github.event.inputs.dockerfile }}
        context: ${{ github.event.inputs.context }}
        push: true
        tags: |
          codiy/${{ github.event.inputs.context }}:latest

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: codiy/${{ github.event.inputs.context }}
        short-description: ${{ github.event.inputs.description }}
        readme-filepath: ${{ github.event.inputs.context }}/${{ github.event.inputs.readme_filepath }}
