name: Docker Images Publish

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Specify build location'
        required: true
        default: 'cloudreve'
      dockerfile:
        description: 'Specify Dockerfile location'
        required: true
        default: 'Dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/386
        file: ${{ github.event.inputs.location }}/${{ github.event.inputs.dockerfile }}
        context: ${{ github.event.inputs.location }}
        push: true
        tags: |
          codiy/${{ github.event.inputs.location }}
